name: Close Stale Issues

permissions:
  issues: write

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  stale-resolved-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        name: Close issues labeled as resolved after 1 week of inactivity
        with:
          any-of-labels: "Resolution-Answered,Resolution-Duplicate,Resolution-External,Resolution-Fixed,Resolution-Inactive"
          stale-issue-label: "Needs: Fix Verification"
          days-before-stale: 0
          days-before-close: 7
          labels-to-remove-when-stale: "Needs: Maintainer Attention,Needs: Triage"
          labels-to-add-when-unstale: "Needs: Maintainer Attention"
          exempt-issue-labels: "Needs: Maintainer Attention"
          close-issue-reason: completed
          close-issue-message: "This issue has been labeled as resolved and has not had any activity a week. It has been closed for housekeeping purposes."
  stale-feedback-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        name: Close issues labeled as needs feedback after 1 week of inactivity
        with:
          stale-issue-label: "Needs: Author Feedback"
          days-before-stale: -1
          days-before-close: 7
          labels-to-remove-when-stale: "Needs: Maintainer Attention,Needs: Triage"
          labels-to-add-when-unstale: "Needs: Maintainer Attention"
          close-issue-reason: completed
          close-issue-message: "This issue has been labeled as needing feedback and has not had any activity a week. It has been closed for housekeeping purposes."
